apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: nokube-system
type: Opaque
data:
  # Postgres / NoKube2024!
  POSTGRES_USER: UG9zdGdyZXM= # Base64 encoded value of "Postgres"
  POSTGRES_PASSWORD: Tm9LdWJlMjAyNCE= # Base64 encoded value of "NoKube2024!"
  POSTGRES_DB: Tm9LdWJlX2Ri # Base64 encoded value of "NoKube_db"