apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: nokube-dev
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP