apiVersion: v1
kind: Service
metadata:
  name: build-service
  namespace: nokube-dev
  labels:
    app: build-service
spec:
  selector:
    app: build-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP