apiVersion: v1
kind: Secret
metadata:
  name: build-secret
  namespace: nokube-dev
  labels:
    app: build-service
type: Opaque
data:
  # Base64 encoded values
  GHCR_USERNAME: # Username
  GHCR_TOKEN:  # New GitHub token
  GITHUB_TOKEN:   # New GitHub token 
