apiVersion: v1
kind: Secret
metadata:
  name: build-secret
  namespace: nokube-dev
  labels:
    app: build-service
type: Opaque
data:
  # Base64 encoded values
  GHCR_USERNAME: QW16aG0=  # Amzhm
  GHCR_TOKEN: Z2hwX1J2Unk1TkRuMzZaVDVOY0lxQU5PejlZdXVQNnMwMzB3Z1Rabg==  # New GitHub token  
  GITHUB_TOKEN: Z2hwX1J2Unk1TkRuMzZaVDVOY0lxQU5PejlZdXVQNnMwMzB3Z1Rabg==  # New GitHub token