apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-service
  namespace: nokube-dev
  labels:
    app: build-service
spec:
  replicas: 2  # Peut avoir plusieurs replicas avec GitHub Actions
  selector:
    matchLabels:
      app: build-service
  template:
    metadata:
      labels:
        app: build-service
    spec:
      containers:
      - name: build-service
        image: nokube/build-service:latest
        imagePullPolicy: Never  # For Kind local images
        ports:
        - containerPort: 8000
        env:
        - name: DOCKER_REGISTRY
          value: "ghcr.io"
        - name: DOCKER_NAMESPACE
          value: "amzhm"
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: build-secret
              key: GITHUB_TOKEN
        - name: GITHUB_BUILD_REPO
          value: "Amzhm/NoKube-build"
        - name: GHCR_USERNAME
          valueFrom:
            secretKeyRef:
              name: build-secret
              key: GHCR_USERNAME
        - name: GHCR_TOKEN
          valueFrom:
            secretKeyRef:
              name: build-secret
              key: GHCR_TOKEN
        - name: BUILD_TIMEOUT
          value: "600"
        - name: MAX_CONCURRENT_BUILDS
          value: "3"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
