apiVersion: v1
kind: Secret
metadata:
  name: build-secret
  namespace: nokube-dev
  labels:
    app: build-service
type: Opaque
data:
  # Base64 encoded values
  GHCR_USERNAME: QW16aG0=  # Amzhm
  GHCR_TOKEN: Z2hwX1p0bWY3MlRzeFNyM0JuaVNxU2FVb1hUVVlVc0Y2QTRRejVveQ==  # New GitHub token 2025-08-18
  GITHUB_TOKEN: Z2hwX1p0bWY3MlRzeFNyM0JuaVNxU2FVb1hUVVlVc0Y2QTRRejVveQ==  # New GitHub token 2025-08-18