apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: nokube-dev
  labels:
    app: api-gateway
    tier: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        tier: gateway
    spec:
      containers:
      - name: api-gateway
        image: nokube/api-gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:80"
        - name: PROJECT_SERVICE_URL
          value: "http://project-service:8000"
        - name: BUILD_SERVICE_URL
          value: "http://build-service:8000"
        - name: MONITOR_SERVICE_URL
          value: "http://monitor-service:8000"
        - name: SERVICE_TIMEOUT
          value: "30"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"