apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
  namespace: nokube-dev
  labels:
    app: project-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
        tier: backend
    spec:
      containers:
      - name: project-service
        image: nokube/project-service:latest
        imagePullPolicy: Never  # Important pour Kind
        ports:
        - containerPort: 8000
        env:
        # Configuration base de données PostgreSQL partagée
        - name: DB_HOST
          value: "postgresql-service.nokube-system.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: DB_PASSWORD
        # Configuration des projets
        - name: MAX_PROJECTS_PER_USER
          value: "20"
        - name: PROJECT_NAMESPACE_PREFIX
          value: "nokube-project-"
        - name: DEFAULT_REPLICAS
          value: "2"
        # Limites de ressources par défaut pour les projets
        - name: DEFAULT_CPU_LIMIT
          value: "500m"
        - name: DEFAULT_MEMORY_LIMIT
          value: "512Mi"
        - name: DEFAULT_CPU_REQUEST
          value: "100m"
        - name: DEFAULT_MEMORY_REQUEST
          value: "128Mi"
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        # Ressources du service lui-même
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"