apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: nokube-dev
  labels:
    app: project-service
    tier: backend
spec:
  selector:
    app: project-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP